---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment.yaml
  - target:
      kind: Service
      name: acme-node
    patch: |-
      - op: add
        path: /spec/selector/environment
        value: sandbox
  - target:
      kind: HTTPRoute
      name: acme-node-route
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "sandbox.ziichat.dev"
      # - op: add
      #   path: /spec/hostnames/-
      #   value: "*.ziichat.dev"
      - op: add
        path: /metadata/annotations
        value: {}
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: sandbox.ziichat.dev
