apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- http-route.yaml
images:
- name: acme-node
  newName: ghcr.io/gitops-ziichat/acme-node
  newTag: 8be0c3d5ae5338d51e86a3c45ffc9b8cb0562d92
