apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- http-route.yaml
images:
- name: acme-node
  newName: ghcr.io/gitops-ziichat/acme-node
  newTag: f4bf05c174c683a6270c2243355e60d4f2301015
